### ISSUE TITLE
Helm install registration fails

### ISSUE THREAD

**Issue by lamw** [vmware/script-runtime-service-for-vsphere#60]
After deploying the SRS Appliance, I attempted the `helm` register command but it failed without any details. 

```
helm install ~/srs --generate-name --set vc.address='192.168.30.3' --set vc.user='srs@vsphere.local' --set vc.password='VMware1!' --set srs.service.hostname='srs.primp-industries.local' --set vc.tls_thumbprint='fcf4c175f40922d98c22105498fa8667fd3b9ac7'
Error: failed post-install: pod srs-1616623839-register failed
```

Look at the SRS register container logs, I see the following:

```
kubectl -n script-runtime-service logs srs-1616623839-register

....
dbug: VMware.ScriptRuntimeService.Setup.SetupFlows.RegisterWithVCSetupFlow[0]
      Resolved SSO SDK Endpoint: https://vcsa.primp-industries.local/sso-adminserver/sdk/vsphere.local
dbug: VMware.ScriptRuntimeService.Setup.SetupFlows.RegisterWithVCSetupFlow[0]
      Resolved Sts Endpoint: https://vcsa.primp-industries.local/sts/STSService/vsphere.local
info: VMware.ScriptRuntimeService.Setup.SsoSolutionUserRegistration[0]
      Performing operation: Solution user registration
fail: VMware.ScriptRuntimeService.Setup.SsoSolutionUserRegistration[0]
      System.AggregateException: One or more errors occurred. (There was no endpoint listening at https://vcsa.primp-industries.local/sts/STSService/vsphere.local that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.)
       ---> System.ServiceModel.EndpointNotFoundException: There was no endpoint listening at https://vcsa.primp-industries.local/sts/STSService/vsphere.local that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
       ---> System.Net.Http.HttpRequestException: Name or service not known
       ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at System.ServiceModel.Channels.HttpChannelFactory`1.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(Message message, TimeoutHelper timeoutHelper)
         --- End of inner exception stack trace ---
         at System.Runtime.AsyncResult.End[TAsyncResult](IAsyncResult result)
         at System.ServiceModel.Channels.ServiceChannel.SendAsyncResult.End(SendAsyncResult result)
         at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
         at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass1_0.<CreateGenericTask>b__0(IAsyncResult asyncResult)
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at System.Threading.Tasks.Task`1.get_Result()
         at VMware.ScriptRuntimeService.Sts.STSClient.<>c__DisplayClass8_0.<IssueBearerTokenByUserCredential>b__0() in /build/mts/release/bora-17270912/cayman_script-runtime-service-for-vsphere/script-runtime-service-for-vsphere/src/src/vSphereIntegrationLibraries/VMware.ScriptRuntimeService.Sts/STSClient.cs:line 160
         at VMware.ScriptRuntimeService.WsTrust.SecurityContext.WsSecurityContext.InvokeOperation[T](Func`1 operation) in /build/mts/release/bora-17270912/cayman_script-runtime-service-for-vsphere/script-runtime-service-for-vsphere/src/src/vSphereIntegrationLibraries/VMware.ScriptRuntimeService.WsTrust/SecurityContext/WsSecurityContext.cs:line 64
         at VMware.ScriptRuntimeService.Sts.STSClient.IssueBearerTokenByUserCredential(String username, SecureString password) in /build/mts/release/bora-17270912/cayman_script-runtime-service-for-vsphere/script-runtime-service-for-vsphere/src/src/vSphereIntegrationLibraries/VMware.ScriptRuntimeService.Sts/STSClient.cs:line 159
         at VMware.ScriptRuntimeService.SsoAdmin.SsoAdminClient.CreateAuthorizedInvocationContext(String authorizationUsername, SecureString authorizationPassword) in /build/mts/release/bora-17270912/cayman_script-runtime-service-for-vsphere/script-runtime-service-for-vsphere/src/src/vSphereIntegrationLibraries/VMware.ScriptRuntimeService.SsoAdmin/SsoAdminClient.cs:line 113
         at VMware.ScriptRuntimeService.SsoAdmin.SsoAdminClient.CreateLocalSolutionUser(String authorizationUsername, SecureString authorizationPassword, String userName, X509Certificate2 certificate, String description) in /build/mts/release/bora-17270912/cayman_script-runtime-service-for-vsphere/script-runtime-service-for-vsphere/src/src/vSphereIntegrationLibraries/VMware.ScriptRuntimeService.SsoAdmin/SsoAdminClient.cs:line 149
         at VMware.ScriptRuntimeService.Setup.SsoSolutionUserRegistration.CreateSolutionUser(String user, SecureString password) in /build/mts/release/bora-17270912/cayman_script-runtime-service-for-vsphere/script-runtime-service-for-vsphere/src/src/Admin/VMware.ScriptRuntimeService.Setup/SsoSolutionUserRegistration.cs:line 38
```

I'm able to manually retrieve the file from SRS, so at least that looks good ... 
```
wget --no-check-certificate https://vcsa.primp-industries.local/sts/STSService/vsphere.local
--2021-03-25 01:02:53--  https://vcsa.primp-industries.local/sts/STSService/vsphere.local
Resolving vcsa.primp-industries.local... 192.168.30.3
Connecting to vcsa.primp-industries.local|192.168.30.3|:443... connected.
WARNING: cannot verify vcsa.primp-industries.local's certificate, issued by ‘OU=VMware Engineering,O=vcsa.primp-industries.local,ST=California,C=US,DC=local,DC=vsphere,CN=CA’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 826 [text/html]
Saving to: ‘vsphere.local’

vsphere.local                                            100%[================================================================================================================================>]     826  --.-KB/s    in 0s
```

**Comment by dmilov** [comment]
Thanks for reporting this one!

'SRS Appliance' is the SRS Host VM deployment, right? 

It looks like DNS issue in the k8s network, I'll investigate and get back to you.

**Comment by welchness** [comment]
I had this same issue and decided to regenerate vmca root and all other certificates on my VCSA using option 4 from VMware KB 2112283 making sure that name, hostname, and vmca name used FQDN and all matched exactly.  I think that did the trick for me as it works now.  I hope that helps.

**Comment by lamw** [comment]
> 'SRS Appliance' is the SRS Host VM deployment, right?

@dmilov That's correct 

> name, hostname, and vmca name used FQDN and all matched exactly

@welchness Interesting but that's not the issue for me. FQDN forward/reverse DNS is used in this setup and I've got other solutions both K8s and non-K8s that use IP/FQDN without issues. This does feel like the Pod isn't able to resolve since resolution is fine within the appliance itself

**Comment by dmilov** [comment]
The issue seems to be related to SSL lib in the SRS container. 
TODO:
Update the Photon OS in images to the latest libssl.

**Comment by cgonzalez-uy** [comment]
same issue...please help me
